name: Publish
on:
  release:
    types:
      - published
      - edited
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu  # https://www.azul.com/downloads/?package=jdk
      - name: Build plugin
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "build/distributions/idea-tcpclient-plugin-*.zip"
